#!/bin/bash
make
rm -f ~/.local/state/thegrid/grid-cli.log
rm -f ~/.local/state/thegrid/events.jsonl
rm -f ~/.local/state/thegrid/grid-server.log
script -q ~/.local/state/thegrid/grid-server.log grid-server/.build/debug/grid-server --debug
