#!/bin/bash
# Build shellcode and extract as C byte arrays

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

echo "🔨 Building shellcode..."

# Compile x86_64 shellcode
echo "  Assembling x86_64 shellcode..."
clang -arch x86_64 -c shellcode_x86_64.s -o shellcode_x86_64.o

# Compile ARM64 shellcode
echo "  Assembling ARM64 shellcode..."
clang -arch arm64 -c shellcode_arm64.s -o shellcode_arm64.o

# Extract x86_64 shellcode bytes
echo "  Extracting x86_64 bytes..."
otool -t shellcode_x86_64.o | grep "^[0-9a-f]" | awk '{for(i=2;i<=NF;i++) print "0x"$i","}' > shellcode_x86_64_bytes.txt

# Extract ARM64 shellcode bytes
echo "  Extracting ARM64 bytes..."
otool -t shellcode_arm64.o | grep "^[0-9a-f]" | awk '{for(i=2;i<=NF;i++) print "0x"$i","}' > shellcode_arm64_bytes.txt

# Generate header file
echo "  Generating shellcode.h..."
cat > shellcode.h << 'EOF'
//
// shellcode.h
// GridSA
//
// Generated shellcode for Mach port injection
// DO NOT EDIT MANUALLY - Generated by build_shellcode.sh
//

#ifndef SHELLCODE_H
#define SHELLCODE_H

#include <stdint.h>
#include <stddef.h>

// x86_64 shellcode
static const uint8_t shellcode_x86_64[] = {
EOF

# Add x86_64 bytes
cat shellcode_x86_64_bytes.txt >> shellcode.h

cat >> shellcode.h << 'EOF'
};

// ARM64 shellcode
static const uint8_t shellcode_arm64[] = {
EOF

# Add ARM64 bytes
cat shellcode_arm64_bytes.txt >> shellcode.h

cat >> shellcode.h << 'EOF'
};

static const size_t shellcode_x86_64_size = sizeof(shellcode_x86_64);
static const size_t shellcode_arm64_size = sizeof(shellcode_arm64);

#endif // SHELLCODE_H
EOF

# Clean up temporary files
rm -f shellcode_x86_64.o shellcode_arm64.o shellcode_x86_64_bytes.txt shellcode_arm64_bytes.txt

echo "✓ Shellcode built successfully"
echo "  x86_64 size: $(wc -c < shellcode.h | awk '{print $1}') bytes"
echo "  Generated: shellcode.h"
